apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cc5550-frontend-service
  name: cc5550-frontend-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cc5550-frontend
  type: LoadBalancer
status:
  loadBalancer: {}