apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cc5550-backend-service
  name: cc5550-backend-service
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: cc5550-backend
status:
  loadBalancer: {}