services:
  web: 
    image: arnasadia/cisc5550todoapp
    build:
      context: frontend
      args:
        api_ip: api
    ports:
      - '5000:5000'
  api: 
    image: arnasadia/cisc5550todoapi
    build:
      context: backend
    ports:
      - '5001:5001'